### PR TITLE
update skywalking protocol v8.4.0

### LINKED ISSUE #36: Tracing.proto and Common.proto pollute global namepace
Tracing.proto and Common.proto introduce lots of symbol into global namepace, like `Command`, `SpanType`.. which conflict with my other header files.
Consider adding `package <NAMESPACE>;` to proto files, however, this will change method name from `/TraceSegmentReportService/collect` to `/<NAMESPACE>.TraceSegmentReportService/collect` which is not recognized by skywalking server. Maybe fix it manually?

### PR DESCRIPTION
**Pull request by Shikugawa**
Also, it fixes #36

### CODE REVIEW

**Comment by wu-sheng** [comment]
Are you using the real SkyWalking or mock collector to run e2e?

**Comment by Shikugawa** [comment]
@wu-sheng Yes. I'm using mock collector.

**Comment by wu-sheng** [comment]
You need to update the mock collector to the latest.

**Comment by Shikugawa** [comment]
@wu-sheng PTAL

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
