### PR TITLE
refactor: refactor the grpc client to get better concurrency support and lifetime management

### PR DESCRIPTION
**Pull request by wbpcode**
See #116

### CODE REVIEW

**Comment by wbpcode** [comment]
There are some concurrency/lifetime problems in the previous impl. This is a refactor to the grpc client.


**IT'S NOT READY FOR MERGE**

**Comment by wbpcode** [comment]
cc @xlj would you mind help to do a quick review and test for this fix in your demo? I have no an accutally scene for the sky2cpp grpc client. 😞

**Comment by wbpcode** [comment]
> @wbpcode It's
> 
> > cc @xlj would you mind help to do a quick review and test for this fix in your demo? I have no an accutally scene for the sky2cpp grpc client. 😞
> 
> @wbpcode it's have "Segmentation fault" error.

Thanks for you help. Could you provider you test code, then I can try it in my local env? Thanks again.

**Comment by xlj** [comment]
> > @wbpcode It's
> > > cc @xlj would you mind help to do a quick review and test for this fix in your demo? I have no an accutally scene for the sky2cpp grpc client. 😞
> > 
> > 
> > @wbpcode it's have "Segmentation fault" error.
> 
> Thanks for you help. Could you provider you test code, then I can try it in my local env? Thanks again.

https://github.com/SkyAPM/cpp2sky/issues/116  
i  pasted my test code in this bug description。

**Comment by jackxuqq** [comment]
> > > @wbpcode It's
> > > > cc @xlj would you mind help to do a quick review and test for this fix in your demo? I have no an accutally scene for the sky2cpp grpc client. 😞
> > > 
> > > 
> > > @wbpcode it's have "Segmentation fault" error.
> > 
> > 
> > Thanks for you help. Could you provider you test code, then I can try it in my local env? Thanks again.
> 
> #116 i pasted my test code in this bug description。



> > > @wbpcode It's
> > > > cc @xlj would you mind help to do a quick review and test for this fix in your demo? I have no an accutally scene for the sky2cpp grpc client. 😞
> > > 
> > > 
> > > @wbpcode it's have "Segmentation fault" error.
> > 
> > 
> > Thanks for you help. Could you provider you test code, then I can try it in my local env? Thanks again.
> 
> #116 i pasted my test code in this bug description。
What's the latest update on

**Pull request closed without merging**
