### PR TITLE
build: introduce header from proto for trace protocol entity

### PR DESCRIPTION
**Pull request by Shikugawa**
Part of #3. Introduce proto -> cpp header for trace protocol entity. Note that it relies on [private fork of skywalking-data-collect-protocol format(v8.1.0)](https://github.com/Shikugawa/skywalking-data-collect-protocol/releases/tag/v8.1.0-bazel) because we'd like to upstream protoc with Bazel.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Do you change the proto file? I haven't found in your fork repo.

**Comment by wu-sheng** [comment]
What don't you add all extra files to this repo? And use the official proto repo of SkyWalking?

**Comment by Shikugawa** [comment]
@wu-sheng yeah we don't have parts which changed for this. It includes only to build protos with bazel. I'd like to upstream them in the future.

**Review by wu-sheng — APPROVED** [review]
Please submit a todo issue to this repo, we need to fix this before 0.1 release.

**Pull request merged**
