### PR TITLE
improve example

### PR DESCRIPTION
**Pull request by Shikugawa**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Should we add client example too?

**Comment by Shikugawa** [comment]
@wu-sheng Is it means another workload to request another endpoint from `/ping` request?

**Comment by wu-sheng** [comment]
My understanding, you wrote a server, right?
We need a client to request this.

Also, the example should include inject, extract, and peer id, right?

**Comment by Shikugawa** [comment]
@wu-sheng like this? https://github.com/SkyAPM/cpp2sky/pull/29/files#diff-19f1088bc098f85759bc09e06f5659961778451f28eca6c6fc38d7c2317ddc66R1

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
