### PR TITLE
e2e: simplify e2e test script

### PR DESCRIPTION
**Pull request by wbpcode**
1. Fix the naming. In previous implementation, the `provider.cc` actually is consumer and the `consumer.cc` actually is provider.
2. Merge two scenarios ([consumer -> provider] and [consumer -> bridge -> provider]) to one test.

### CODE REVIEW

**Comment by wbpcode** [comment]
This should also fixed CI problem in the #132

**Comment by wbpcode** [comment]
The coverage report is broken and we may need to remove it because the codecov only provide limited support to the free users.

**Comment by wbpcode** [comment]
friendly ping @wu-sheng

**Comment by wu-sheng** [comment]
I can see you changed the CI names. Is that expected? And, there is one CI process fails.

**Comment by wu-sheng** [comment]
I could change the required CIs, if those new names are expected.

**Comment by wbpcode** [comment]
> I can see you changed the CI names. Is that expected? And, there is one CI process fails.

The coverage reporting is broken. /sad

**Comment by wu-sheng** [comment]
How about we remove that to keep CI green?

**Comment by wbpcode** [comment]
> New UT fail should be fixed?

I am inclined to remove the coverage reporting from the CI and add a simple coverage ratio checking in our CI directly.

**Comment by wu-sheng** [comment]
Please go ahead. Personally, I am not a fun about coverage rate.
Once codes are tested through CI, it is good. No matter how coverage says.

**Comment by wu-sheng** [comment]
Should I merge first or wait foe your update?

**Comment by wbpcode** [comment]
If you don't care it's coverage ratio, then I can remove the failed coverage reporting directly in this PR. :)

**Comment by wbpcode** [comment]
I will push the new commit tonight

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
