### PR TITLE
fix encoding errors caused by string_view that does not end with '\0'

### PR DESCRIPTION
**Pull request by wbpcode**
Signed-off-by: wbpcode <comems@msn.com> / wbphub@live.com

Check #83 get more info.

### CODE REVIEW

**Comment by wbpcode** [comment]
cc @Shikugawa

**Review by Shikugawa — APPROVED** [review]
Thanks!

**Comment by Shikugawa** [comment]
@wbpcode Does this bug affect upstream Envoy tracer? If so, we should release a new version of cpp2sky to include the next release of Envoy.

**Comment by wbpcode** [comment]
@Shikugawa 
In envoy, we can bypass this problem by creating a string copy for string_view.
I tried to pass host string_view directly to cpp2sky to reduce unnecessary copy, and found this problem by accident.

**Pull request merged**
